--INSERT INTO SurveyStatus(Name) VALUES ('Status1');
--INSERT INTO SurveyStatus(Name) VALUES ('Status2');
--INSERT INTO SurveyStatus(Name) VALUES ('Status3');

INSERT INTO SHIP(NAME) VALUES('De marie-louise');
INSERT INTO SHIP(NAME) VALUES('De zeeschuimer');

INSERT INTO TAXON(CODE,VALUE) VALUES('0','telling zonder vogels');
INSERT INTO TAXON(CODE,VALUE) VALUES('20','Gavia stellata');
INSERT INTO TAXON(CODE,VALUE) VALUES('30','Gavia arctica');
INSERT INTO TAXON(CODE,VALUE) VALUES('40','Gavia immer');
INSERT INTO TAXON(CODE,VALUE) VALUES('59','Gavia sp.');
INSERT INTO TAXON(CODE,VALUE) VALUES('90','Podiceps cristatus');
INSERT INTO TAXON(CODE,VALUE) VALUES('100','Podiceps grisegena');
INSERT INTO TAXON(CODE,VALUE) VALUES('110','Podiceps auritus');
INSERT INTO TAXON(CODE,VALUE) VALUES('120','Podiceps nigricollis');
INSERT INTO TAXON(CODE,VALUE) VALUES('128','Podiceps auritus / Podiceps nigricollis');
INSERT INTO TAXON(CODE,VALUE) VALUES('129','Podiceps sp.');
INSERT INTO TAXON(CODE,VALUE) VALUES('220','Fulmarus glacialis');
INSERT INTO TAXON(CODE,VALUE) VALUES('360','Calonectris diomedea');
INSERT INTO TAXON(CODE,VALUE) VALUES('400','Puffinus gravis');
INSERT INTO TAXON(CODE,VALUE) VALUES('409','Puffinus gravis / Calonectris diomedea');
INSERT INTO TAXON(CODE,VALUE) VALUES('430','Puffinus griseus');
INSERT INTO TAXON(CODE,VALUE) VALUES('460','Puffinus puffinus');
INSERT INTO TAXON(CODE,VALUE) VALUES('462','Puffinus puffinus mauretanicus');
INSERT INTO TAXON(CODE,VALUE) VALUES('469','Puffinus sp.');
INSERT INTO TAXON(CODE,VALUE) VALUES('480','Puffinus assimilis');
INSERT INTO TAXON(CODE,VALUE) VALUES('520','Hydrobates pelagicus');
INSERT INTO TAXON(CODE,VALUE) VALUES('550','Oceanodroma leucorhoa');
INSERT INTO TAXON(CODE,VALUE) VALUES('558','Oceanodroma leucorhoa / Hydrobates pelagicus');
INSERT INTO TAXON(CODE,VALUE) VALUES('710','Sula bassana');
INSERT INTO TAXON(CODE,VALUE) VALUES('720','Phalacrocorax carbo');
INSERT INTO TAXON(CODE,VALUE) VALUES('800','Phalacrocorax aristotelis');
INSERT INTO TAXON(CODE,VALUE) VALUES('1210','Egretta alba');
INSERT INTO TAXON(CODE,VALUE) VALUES('1220','Ardea cinerea');
INSERT INTO TAXON(CODE,VALUE) VALUES('1234','test');
INSERT INTO TAXON(CODE,VALUE) VALUES('1440','Platalea leucorodia');
INSERT INTO TAXON(CODE,VALUE) VALUES('1520','Cygnus olor');
INSERT INTO TAXON(CODE,VALUE) VALUES('1549','Cygnus sp.');
INSERT INTO TAXON(CODE,VALUE) VALUES('1580','Anser brachyrhynchus');
INSERT INTO TAXON(CODE,VALUE) VALUES('1590','Anser albifrons');
INSERT INTO TAXON(CODE,VALUE) VALUES('1610','Anser anser');
INSERT INTO TAXON(CODE,VALUE) VALUES('1620','Anser indicus');
INSERT INTO TAXON(CODE,VALUE) VALUES('1639','Anser sp.');
INSERT INTO TAXON(CODE,VALUE) VALUES('1660','Branta canadensis');
INSERT INTO TAXON(CODE,VALUE) VALUES('1670','Branta leucopsis');
INSERT INTO TAXON(CODE,VALUE) VALUES('1680','Branta bernicla');
INSERT INTO TAXON(CODE,VALUE) VALUES('1699','Anser sp. / Branta sp.');
INSERT INTO TAXON(CODE,VALUE) VALUES('1700','Alopochen aegyptiacus');
INSERT INTO TAXON(CODE,VALUE) VALUES('1730','Tadorna tadorna');
INSERT INTO TAXON(CODE,VALUE) VALUES('1790','Anas penelope');
INSERT INTO TAXON(CODE,VALUE) VALUES('1820','Anas strepera');
INSERT INTO TAXON(CODE,VALUE) VALUES('1840','Anas crecca');
INSERT INTO TAXON(CODE,VALUE) VALUES('1860','Anas platyrhynchos');
INSERT INTO TAXON(CODE,VALUE) VALUES('1890','Anas acuta');
INSERT INTO TAXON(CODE,VALUE) VALUES('1910','Anas querquedula');
INSERT INTO TAXON(CODE,VALUE) VALUES('1940','Anas clypeata');


INSERT INTO AGE(CODE,VALUE) VALUES('A','Adult');
INSERT INTO AGE(CODE,VALUE) VALUES('I','Immatuur');
INSERT INTO AGE(CODE,VALUE) VALUES('J','Juveniel');

INSERT INTO PLUMAGE(CODE,VALUE) VALUES('1','Eerste kalenderjaar');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('2','Tweede kalenderjaar');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('3','Derde kalenderjaar');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('4','Vierde kalenderjaar');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('5','Vijfde kalenderjaar');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('6','Zesde kalenderjaar');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('B','Broedkleed');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('D','Donkere fase');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('F','Female');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('G','Graellsii');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('I','Intermedius');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('L','Lichte fase');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('M','Male');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('T','Overgangskleed (transit)');
INSERT INTO PLUMAGE(CODE,VALUE) VALUES('W','Winterkleed');

INSERT INTO STRATUM(CODE,VALUE) VALUES('0','Nultelling');
INSERT INTO STRATUM(CODE,VALUE) VALUES('1','Vliegt op 0-100m');
INSERT INTO STRATUM(CODE,VALUE) VALUES('2','Vliegt op 100-1000m');
INSERT INTO STRATUM(CODE,VALUE) VALUES('3','Vliegt op >1000m');
INSERT INTO STRATUM(CODE,VALUE) VALUES('A','Zit op 0-50m');
INSERT INTO STRATUM(CODE,VALUE) VALUES('B','Zit op 50-100m');
INSERT INTO STRATUM(CODE,VALUE) VALUES('C','Zit op 100-200m');
INSERT INTO STRATUM(CODE,VALUE) VALUES('D','Zit op 200-300m');
INSERT INTO STRATUM(CODE,VALUE) VALUES('E','Zit op >300m');
INSERT INTO STRATUM(CODE,VALUE) VALUES('U','Zit op onbekende afstand');


INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('1','Vliegt naar noorden');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('2','Vliegt naar noordoosten');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('3','Vliegt naar oosten');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('4','Vliegt naar zuidoosten');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('5','Vliegt naar zuiden');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('6','Vliegt naar zuidwesten');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('7','Vliegt naar westen');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('8','Vliegt naar noordwesten');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('9','Vliegt rond');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('F','Vis/voedsel in bek');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('K','Kleptoparasiterend');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('M','Duidelijke trekbeweging');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('P','Pikkend');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('R','Rustend');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('S','Pikt aan kadaver');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('U','Unhappy');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('X','Dood');
INSERT INTO FLYWAYBEHAVIOUR(CODE,VALUE) VALUES('Y','Duikend');



INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('A','Ander schip');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('B','Boei');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('C','Naar kolonie zonder vis');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('D','Drijfvuil');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('E','Met eigen schip');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('H','Hout, balk, pallet');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('K','Kust (bv zandbank)');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('L','stroomnaad');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('M','Naar kolonie met vis');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('N','Vliegt naar land');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('O','Olievlek');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('P','Platform');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('Q','Vliegt naar kolonie');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('T','Turbines');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('V','Vissersboot');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('W','Wierveld');
INSERT INTO ASSOCIATIONBEHAVIOUR(CODE,VALUE) VALUES('X','Binnen windpark');

INSERT INTO TURBINEHEIGHT(CODE,VALUE) VALUES('1','Vogel vliegt ter hoogte van de rotor');
INSERT INTO TURBINEHEIGHT(CODE,VALUE) VALUES('2','Vogel vliegt boven de rotor');




--INSERT INTO TRIP() VALUES ();

--INSERT INTO OBSERVATION() VALUES();